### ISSUE TITLE
scroll on mobile resets carousel to first slide

### ISSUE THREAD

**Issue by bfang212** [maxmarinich/react-alice-carousel#108] opened 2020-01-16 18:09 UTC
This occurs both for mobile on Safari and Chrome and works completely fine on desktop.
Take the demo example. [1, 2, 3, 4, 5]:
If I swipe to 2, and I scroll down and past of the Carousel component on my phone, the Carousel resets to 1. I have inspected the DOM and the `active` classname switches to 1.
This is only occurring on versions after 1.13.0 and was discovered because I wanted to use autoHeight. 

I attached a mp4 for you to check out.

[RPReplay_Final1579197970.MP4.zip](https://github.com/maxmarinich/react-alice-carousel/files/4072967/RPReplay_Final1579197970.MP4.zip)

**Comment by maxmarinich** [comment] 2020-01-28 07:26
Hi, @bfang212! Fixed in #111

**Comment by juanfe190** [comment] 2020-03-03 17:31
Issue is still happening after fix.

**Comment by maxmarinich** [comment] 2020-03-05 13:57
@juanfe190, the issue isn't reproduced. Not reproduced. Checked in v1.17.3. Try [this](https://codesandbox.io/s/vq1y9z3x80).

**Closed by maxmarinich** 2020-03-05 13:57 UTC
Labels: bug
