### ISSUE TITLE
Blurry Images from transfrom translate3d

### ISSUE THREAD

**Issue by sbauschl** [maxmarinich/react-alice-carousel#86] opened 2019-10-07 14:49 UTC
Depending on the container size of the carousel, the translate 3d can often have percentages in it.
i.e. translate3d(-1570.33px, 0px, 0px)

This causes the images to be blurry as shown below. The translate3d css should always be rounded to the nearest whole number to avoid the blur.

![Untitled](https://user-images.githubusercontent.com/55113917/66322247-ce734780-e8ef-11e9-90b3-df59a0bb0642.png)

**Comment by maxmarinich** [comment] 2019-10-07 15:58
Hi, @sbauschl! 
Duplicate of #72

**Closed by maxmarinich** 2019-10-07 15:58 UTC

**Comment by sbauschl** [comment] 2019-10-07 19:42
Yeah I guess it mostly is the browsers fault... Although no fix online, included the backface visibility one works currently for this. I'll just wait for chrome to fix if rounding doesn't make sense. Thanks for the quick reply.
